[mypy]
disallow_untyped_defs = True
disallow_untyped_decorators = True
disallow_any_generics = True

[mypy-pyghidra]
ignore_missing_imports = True

[mypy-org.xml.sax.helpers]
ignore_missing_imports = True

[mypy-java.util]
ignore_missing_imports = True
