# Config file with less build variants for testing purposes

# Optimizations

optimizations:
  O0: "-Wall -g -O0"
  O1: "-Wall -g -O1"
  O2: "-Wall -g -O2"

# Libraries to analyze

libraries:
  - name: openssl
    available_versions: ["3.0.0", "3.5.5"]
    archives: "libcrypto.a;libssl.a"
    download_script: |
      cd {download_path}
      wget https://github.com/openssl/openssl/archive/refs/tags/openssl-{version}.tar.gz
      tar -xvzf openssl-{version}.tar.gz
      mv openssl-openssl-{version} openssl-{version}
      mv openssl-{version} {source_path}/..
    build_script: |
      cd {build_path}
      CFLAGS="{compiler_flags}" CXXFLAGS="{compiler_flags}" {source_path}/Configure
      make

  - name: libpng
    available_versions: ["1.6.34", "1.6.58"]
    archives: "lib/libpng16.a"
    download_script: |
      cd {download_path}
      wget https://github.com/pnggroup/libpng/archive/refs/tags/v{version}.tar.gz
      tar -xvzf v{version}.tar.gz
      mv libpng-{version} {source_path}/..
    build_script: |
      cd {source_path}
      cp scripts/makefile.std Makefile
      cmake . -DCMAKE_INSTALL_PREFIX={build_path} -DCMAKE_C_FLAGS="{compiler_flags}"
      make
      make install